In [1]:
from eye_analysis import get_values
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
project_dir = "/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/mix_data"

In [12]:
df = get_values(project_dir, dv="Pupil_l", iv=["group", "age", "gender", "GDS_15_total_score"], iv_val=None)

In [13]:
df.head(70)

,Subj,n,group,age,gender,GDS_15_total_score,Pupil_l
0,2,231,2,68,M,13.0,"[-0.12957692666466727, -0.12936674365729073, -..."
1,3,216,1,67,F,0.0,"[-0.012522129106855502, -0.012726815872173065,..."
2,4,232,2,70,F,8.0,"[-0.14076786934767027, -0.14137924549346062, -..."
3,5,20,2,66,F,12.0,"[-0.137693051734374, -0.13936772767584127, -0...."
4,6,108,2,69,M,4.0,"[-0.025608818021865275, -0.025703713031506568,..."
5,8,212,2,73,F,12.0,"[-0.027007379034343727, -0.02712782427681164, ..."
6,9,6,1,79,M,0.0,"[0.029514655742676938, 0.02891499327980666, 0...."
7,10,3,2,68,F,10.0,"[-0.0007807552122556238, 0.0011234939790285559..."
8,12,216,1,71,F,0.0,"[-0.07153583898033827, -0.07215312675742656, -..."
9,13,41,1,79,M,0.0,"[-0.5919123116721086, -0.5918402860008707, -0...."
10,14,225,1,73,F,1.0,"[-0.2817540559299483, -0.2816951034924415, -0...."
11,16,228,2,66,M,11.0,"[-0.12219486334794814, -0.12198149911071493, -..."
12,17,214,2,76,M,11.0,"[-0.015684569952305803, -0.015612170919855636,..."
13,18,190,2,72,F,15.0,"[-0.02653072818657217, -0.02653135309421634, -..."
14,19,200,1,73,F,3.0,"[-0.011680473080321926, -0.011607521167441983,..."
15,20,236,1,70,F,0.0,"[-0.011379310765890868, -0.011438961882084219,..."
16,21,209,1,73,M,2.0,"[-0.020509530735236075, -0.02042722898395784, ..."
17,22,204,1,73,F,2.0,"[-0.04152390457643974, -0.041847914256720235, ..."
18,23,226,1,79,F,NaN,"[-0.009906165551431773, -0.009943949093997312,..."
19,25,214,1,79,M,0.0,"[0.018515699097771766, 0.018456452637917783, 0..."
20,26,128,1,72,F,1.0,"[0.004990425034986794, 0.004903549402581513, 0..."
21,27,54,1,73,F,4.0,"[-0.10314761613731953, -0.10412740832603458, -..."
22,28,223,1,71,F,0.0,"[-0.04733552989228237, -0.04765961878861894, -..."
23,29,233,1,67,F,3.0,"[-0.032464899620820366, -0.03252023831256453, ..."
24,30,224,2,69,F,9.0,"[-0.06839891196928218, -0.06890185064005364, -..."
25,31,203,2,61,F,12.0,"[-0.01827971049390277, -0.018333608360964593, ..."
26,32,182,2,72,M,11.0,"[-0.004353633319808233, -0.00428672284857323, ..."
27,33,203,1,80,M,2.0,"[-0.019251885590703923, -0.01917744144471204, ..."
28,35,204,2,75,F,13.0,"[-0.10769457554145044, -0.10828217799786116, -..."
29,36,231,1,78,M,1.0,"[-0.004309479551649476, -0.004301154511567081,..."
30,37,202,2,68,F,8.0,"[-0.07024185657266332, -0.07070364975458314, -..."
31,38,210,2,70,M,7.0,"[0.016822035186693465, 0.016756513219850087, 0..."
32,39,177,2,80,M,11.0,"[-0.05359378517298954, -0.05411384142339473, -..."
33,40,227,1,65,F,NaN,"[-0.09820906564710556, -0.09873555268668001, -..."
34,41,231,2,71,M,6.0,"[-0.07143467886417966, -0.07168186938918505, -..."
35,42,219,2,70,F,11.0,"[-0.11304557503005006, -0.11374769161744072, -..."
36,43,212,2,78,F,7.0,"[-0.0077620242488649314, -0.00798774141554964,..."
37,44,209,2,68,M,NaN,"[-0.015836676850015042, -0.01591502416108057, ..."
38,46,226,1,69,F,1.0,"[2.3326822133993147e-05, -0.000177769754792989..."
39,47,222,1,66,F,0.0,"[0.027208466215887257, 0.027163131245258362, 0..."
40,48,228,1,83,M,NaN,"[-0.024976220671560634, -0.025003317779631946,..."
41,49,220,1,85,M,3.0,"[-0.04672634315296627, -0.047031214408667504, ..."
42,50,192,1,69,M,NaN,"[0.00802922992045012, 0.007981404643598465, 0...."
43,51,33,2,78,F,10.0,"[-0.0025176142524777926, -0.002796159400922690..."
44,52,224,1,69,F,1.0,"[-0.14158513602438594, -0.14186571850345414, -..."
45,53,19,1,67,F,2.0,"[-0.15983021805566722, -0.16078928816096894, -..."
46,54,234,1,68,M,NaN,"[-0.017042980974931145, -0.017108276080237655,..."
47,55,228,2,69,F,11.0,"[0.004812694640541253, 0.004860841599477978, 0..."
48,56,9,2,72,F,7.0,"[-0.13733098057503856, -0.13766206450855092, -..."
49,57,7,2,67,F,14.0,"[-0.11831188693314308, -0.11998667527194051, -..."
50,58,126,1,66,F,0.0,"[-0.07555340596551269, -0.07542457856772719, -..."
51,60,231,1,73,F,5.0,"[-0.021762790980015226, -0.022321584266755748,..."
52,62,233,2,72,F,7.0,"[-0.020144898558559964, -0.02043398466711558, ..."
53,63,218,2,81,F,10.0,"[-0.18976331060210988, -0.1913509267963887, -0..."
54,64,8,2,81,F,13.0,"[-0.2133034263084186, -0.21480880121686585, -0..."
55,65,221,2,65,F,11.0,"[0.001492430938846419, 0.0014780438340007247, ..."
56,67,210,2,76,F,12.0,"[-0.2131628959672029, -0.21502195348448164, -0..."
57,68,226,2,71,F,14.0,"[-0.19449734723495, -0.19552558959934396, -0.1..."
58,69,219,2,67,M,4.0,"[-0.034611868152598035, -0.03499424365202726, ..."

In [7]:
df = get_values(project_dir, dv="Pupil_l", iv=["group", "age", "gender", "GDS_15_total_score"], iv_val=None)
df2 = get_values(project_dir, dv="Pupil_r", iv=["group", "age", "gender", "GDS_15_total_score"], iv_val=None)
df3 = get_values(project_dir, dv="Rate", iv=["group", "age", "gender", "GDS_15_total_score"], iv_val=None)
df4 = get_values(project_dir, dv="Amp", iv=["group", "age", "gender", "GDS_15_total_score"], iv_val=None)
df5 = get_values(project_dir, dv="Vel", iv=["group", "age", "gender", "GDS_15_total_score"], iv_val=None)
df6 = get_values(project_dir, dv="Ang", iv=["group", "age", "gender", "GDS_15_total_score"], iv_val=None)
df7 = get_values(project_dir, dv="Cos", iv=["group", "age", "gender", "GDS_15_total_score"], iv_val=None)
df8 = get_values(project_dir, dv="Sin", iv=["group", "age", "gender", "GDS_15_total_score"], iv_val=None)

/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice
  mean_mat.append(np.nanmean(dvar[:, valid_idx], axis=1))
/Users/aryansmac/Documents/PROJECT/TEEP/TEEP'25/LLD_CTRL_MAIN/Pupil-size-and-microsaccade-analysis-main/new_data/python script/eye_analysis.py:57: RuntimeWarning: Mean of empty slice

In [4]:
df3

,Subj,n,group,age,gender,GDS_15_total_score,Rate
0,2,231,2,68,M,13.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
1,3,216,1,67,F,0.0,"[0.004629629629629629, 0.0023148148148148147, ..."
2,4,232,2,70,F,8.0,"[0.0, 0.0, 0.0028735632183908046, 0.0021551724..."
3,5,20,2,66,F,12.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
4,6,108,2,69,M,4.0,"[0.0, 0.0, 0.0, 0.0023148148148148147, 0.00185..."
5,8,212,2,73,F,12.0,"[0.0, 0.0, 0.0, 0.0011792452830188679, 0.00094..."
6,9,6,1,79,M,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
7,10,3,2,68,F,10.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
8,12,216,1,71,F,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.000..."
9,13,41,1,79,M,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
10,14,225,1,73,F,1.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
11,16,228,2,66,M,11.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
12,17,214,2,76,M,11.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.000778816199376947..."
13,18,190,2,72,F,15.0,"[0.005263157894736842, 0.002631578947368421, 0..."
14,19,200,1,73,F,3.0,"[0.0, 0.0, 0.006666666666666667, 0.005, 0.004,..."
15,20,236,1,70,F,0.0,"[0.00423728813559322, 0.00423728813559322, 0.0..."
16,21,209,1,73,M,2.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.000797448165869218..."
17,22,204,1,73,F,2.0,"[0.004901960784313725, 0.004901960784313725, 0..."
18,23,226,1,79,F,NaN,"[0.0, 0.0, 0.0014749262536873156, 0.0011061946..."
19,25,214,1,79,M,0.0,"[0.0, 0.0, 0.0, 0.0, 0.0009345794392523364, 0...."
20,26,128,1,72,F,1.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
21,27,54,1,73,F,4.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
22,28,223,1,71,F,0.0,"[0.004484304932735426, 0.002242152466367713, 0..."
23,29,233,1,67,F,3.0,"[0.0, 0.002145922746781116, 0.0014306151645207..."
24,30,224,2,69,F,9.0,"[0.004464285714285714, 0.004464285714285714, 0..."
25,31,203,2,61,F,12.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
26,32,182,2,72,M,11.0,"[0.005494505494505495, 0.0027472527472527475, ..."
27,33,203,1,80,M,2.0,"[0.0, 0.0, 0.0, 0.0012315270935960591, 0.00098..."
28,35,204,2,75,F,13.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.000..."
29,36,231,1,78,M,1.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.000721500721500721..."
30,37,202,2,68,F,8.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0007072135785..."
31,38,210,2,70,M,7.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
32,39,177,2,80,M,11.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
33,40,227,1,65,F,NaN,"[0.004405286343612335, 0.004405286343612335, 0..."
34,41,231,2,71,M,6.0,"[0.0, 0.0021645021645021645, 0.001443001443001..."
35,42,219,2,70,F,11.0,"[0.0, 0.0, 0.0, 0.001141552511415525, 0.000913..."
36,43,212,2,78,F,7.0,"[0.018867924528301886, 0.01650943396226415, 0...."
37,44,209,2,68,M,NaN,"[0.0, 0.0, 0.0, 0.0011961722488038277, 0.00095..."
38,46,226,1,69,F,1.0,"[0.0, 0.0, 0.0, 0.0, 0.0008849557522123894, 0...."
39,47,222,1,66,F,0.0,"[0.0045045045045045045, 0.0022522522522522522,..."
40,48,228,1,83,M,NaN,"[0.0043859649122807015, 0.0021929824561403508,..."
41,49,220,1,85,M,3.0,"[0.0, 0.0022727272727272726, 0.001515151515151..."
42,50,192,1,69,M,NaN,"[0.0, 0.005208333333333333, 0.0052083333333333..."
43,51,33,2,78,F,10.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
44,52,224,1,69,F,1.0,"[0.0, 0.002232142857142857, 0.0014880952380952..."
45,53,19,1,67,F,2.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
46,54,234,1,68,M,NaN,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.000712250712250712..."
47,55,228,2,69,F,11.0,"[0.0, 0.0, 0.0029239766081871343, 0.0032894736..."
48,56,9,2,72,F,7.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
49,57,7,2,67,F,14.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
50,58,126,1,66,F,0.0,"[0.007936507936507936, 0.007936507936507936, 0..."
51,60,231,1,73,F,5.0,"[0.0, 0.0, 0.001443001443001443, 0.00324675324..."
52,62,233,2,72,F,7.0,"[0.0, 0.0, 0.001430615164520744, 0.00214592274..."
53,63,218,2,81,F,10.0,"[0.0, 0.0, 0.0, 0.0, 0.0009174311926605505, 0...."
54,64,8,2,81,F,13.0,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ..."
55,65,221,2,65,F,11.0,"[0.0, 0.0022624434389140274, 0.001508295625942..."
56,67,210,2,76,F,12.0,"[0.0, 0.0, 0.0, 0.0, 0.0009523809523809525, 0...."
57,68,226,2,71,F,14.0,"[0.0, 0.0, 0.0, 0.0011061946902654867, 0.00265..."
58,69,219,2,67,M,4.0,"[0.0, 0.0, 0.0, 0.0, 0.0009132420091324201, 0...."

In [8]:
# Use LONG (tidy) format: one 'Value' column and a 'DV' label
def to_long(dfin, dv_name):
    keep = [c for c in dfin.columns if c not in {"Pupil_l","Pupil_r","Rate","Amp","Vel","Ang","Cos","Sin"}]
    return dfin[keep + [dv_name]].rename(columns={dv_name: "Value"}).assign(DV=dv_name)

long_df = pd.concat([
    to_long(df,  "Pupil_l"),
    to_long(df2, "Pupil_r"),
    to_long(df3, "Rate"),
    to_long(df4, "Amp"),
    to_long(df5, "Vel"),
    to_long(df6, "Ang"),
    to_long(df7, "Cos"),
    to_long(df8, "Sin"),
], ignore_index=True)

In [12]:
long_df.head(1)

,Subj,n,group,age,gender,GDS_15_total_score,Value,DV
0,2,231,2,68,M,13.0,"[-0.12957692666466727, -0.12936674365729073, -...",Pupil_l